name: food-allergy-app
app: dockerfile

options:
  env:
    - name: NODE_ENV
      value: production
    - name: TZ
      value: Asia/Seoul
  ports: 3001
  dockerfile: Dockerfile

context:
  git:
    url: https://github.com/un4me90/FoodAllergy.git
    branch: main
  preset: dockerfile
