name: food-allergy-app
app: dockerfile

options:
  env:
    - name: NODE_ENV
      value: production
    - name: TZ
      value: Asia/Seoul
  ports: 3001
  dockerfile: Dockerfile

context:
  preset: node.js
